<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1062</NoWarn><!-- Validate arguments of public methods -->
  </PropertyGroup>

</Project>
