<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateSBOM>false</GenerateSBOM>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <Nullable>disable</Nullable>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);IDE0161</NoWarn>    <!-- Convert to file-scoped namespace -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Utilities.Core" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.IO.Redist" PrivateAssets="All" ExcludeAssets="runtime" Condition="'$(TargetFramework)' == 'net472'" />    <!-- https://github.com/advisories/GHSA-hq7w-xv5x-g34j -->
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="../../Global.cs" />
  </ItemGroup>

</Project>
