<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../fixtures/Fixtures/Fixtures.csproj" />
    <ProjectReference Include="../../fixtures/Fixtures.Xunit/Fixtures.Xunit.csproj" />
    <ProjectReference Include="../../src/MinVer.Lib/MinVer.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LogMessages.*.expected.txt">
      <DependentUpon>LogMessages.cs</DependentUpon>
    </None>
    <None Update="Versions.*.expected.txt">
      <DependentUpon>Versions.cs</DependentUpon>
    </None>
  </ItemGroup>

</Project>
