<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />

  <Sdk Name="DotNet.ReproducibleBuilds.Isolated" Version="2.0.5" />

  <PropertyGroup>
    <PackageIcon>icon.png</PackageIcon>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/adamralph/minver</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>https://github.com/adamralph/minver/blob/main/CHANGELOG.md</PackageReleaseNotes>
  </PropertyGroup>

  <!-- MinVer doesn't use MinVer for versioning because
    the environment variables for the build and for the package tests
    would interfere with each other. -->
  <PropertyGroup>
    <Version>0.0.0</Version>
    <Version Condition="'$(MINVER_VERSION)' != ''">$(MINVER_VERSION)</Version>
    <InformationalVersion Condition="'$(BUILD_METADATA)' != ''">$(Version)+$(BUILD_METADATA)</InformationalVersion>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA2007</NoWarn>    <!-- Do not directly await a Task -->
    <NoWarn>$(NoWarn);CS1591</NoWarn>    <!-- Missing XML comment for publicly visible type or member --><!-- workaround for https://github.com/dotnet/roslyn/issues/41640 -->
    <NoWarn>$(NoWarn);VSTHRD111</NoWarn>    <!-- Add .ConfigureAwait(bool) to your await expression -->
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GenerateSBOM>true</GenerateSBOM>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Sbom.Targets" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../assets/icon.png" Pack="true" PackagePath="/" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
