<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);MINVER_CLI</DefineConstants>
    <Description>A minimalist .NET tool, developed by humans, for versioning any kind of software or content using Git tags.</Description>
    <IsPackable>true</IsPackable>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <RollForward>major</RollForward>
    <RootNamespace>MinVer</RootNamespace>
    <ToolCommandName>minver</ToolCommandName>
  </PropertyGroup>

  <!-- workaround for https://github.com/dotnet/command-line-api/issues/403 -->
  <PropertyGroup>
    <AssemblyName>minver</AssemblyName>
    <PackageId>minver-cli</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MinVer.Lib\MinVer.Lib.csproj" />
  </ItemGroup>

</Project>
