name: ci-test-packages
on:
  push:
    branches: [main, release-*]
  pull_request:
  workflow_dispatch:
permissions: read-all
env:
  DOTNET_NOLOGO: true
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-26
            sdk: "10.0.201"
          - os: ubuntu-24.04
            sdk: "8.0.419"
          - os: ubuntu-24.04
            sdk: "9.0.312"
          - os: ubuntu-24.04
            sdk: "10.0.201"
          - os: ubuntu-24.04-arm
            sdk: "8.0.419"
          - os: ubuntu-24.04-arm
            sdk: "9.0.312"
          - os: ubuntu-24.04-arm
            sdk: "10.0.201"
            upload-packages: true
          - os: windows-2025
            sdk: "10.0.201"
          - os: windows-11-arm
            sdk: "10.0.201"
    name: ${{ matrix.os }}-sdk-${{ matrix.sdk }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: |
            ${{ matrix.sdk }}
            10.0.201
      - run: dotnet --info
      - run: git --version
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - env:
          MINVER_SDK: ${{ matrix.sdk }}
        run: ./build test-packages
