on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3.17.1
        env:
          FILTER_REGEX_EXCLUDE: \bLICENSE$|\bgeneral\.txt$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SHELL_SHFMT: false
